Hcm.Web/Controllers/DepartmentController.cs
using Hcm.Api.Client;
using Hcm.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hcm.Web.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentClient _departmentClient;

        public DepartmentController(IDepartmentClient departmentClient)
        {
            _departmentClient = departmentClient;
        }

        // GET: DepartmentController
        public async Task<ActionResult> Index()
        {
            var result = await _departmentClient.GetAllAsync();
            return View(result.Select(e => new DepratmentViewModel
            {
                City = e.City,
                Country = e.Country,
                DepartmentId = e.Id,
                Name = e.Name
            }).ToArray());
        }

        // GET: DepartmentController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var result = await _departmentClient.GetAsync(id);
            return View(new DepratmentViewModel
            {
                City = result.City,
                Country = result.Country,
                DepartmentId = result.Id,
                Name = result.Name
            });
        }

        // GET: DepartmentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DepartmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DepratmentViewModel depratmentViewModel)
        {
            try
            {
                var result = await _departmentClient.PostAsync(new DepartmentCreateDto
                {
                    Name = depratmentViewModel.Name,
                    City = depratmentViewModel.City,
                    Country = depratmentViewModel.Country
                });

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartmentController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var result = await _departmentClient.GetAsync(id);
            return View(new DepratmentViewModel
            {
                City = result.City,
                Country = result.Country,
                DepartmentId = result.Id,
                Name = result.Name
            });
        }

        // POST: DepartmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            string id, 
            DepratmentViewModel depratmentViewModel)
        {
            try
            {
                var result = await _departmentClient.PutAsync(id, new DepartmentUpdateDto
                {
                    Name = depratmentViewModel.Name,
                    City = depratmentViewModel.City,
                    Country = depratmentViewModel.Country,
                    Id = id,
                });

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartmentController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var result = await _departmentClient.GetAsync(id);
            return View(new DepratmentViewModel
            {
                City = result.City,
                Country = result.Country,
                DepartmentId = result.Id,
                Name = result.Name
            });
        }

        // POST: DepartmentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, IFormCollection collection)
        {
            try
            {
                var result = await _departmentClient.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Hcm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hcm.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/hcm/css/style.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">HCM Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 float-left">
                        @if (User.Identity.IsAuthenticated
                       && User.IsInRole("Administrator"))
                        {
                            <li class="main-btns nav-item" >
                                <a class="nav-link text-dark active" asp-area="" asp-controller="Home" asp-action="Index">Employees</a>
                            </li>
                            <li class="main-btns nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                            </li>

                            // TODO add navigation for "Users" this should lead people to the page for managing administrators
                        }

                        @if (User.Identity.IsAuthenticated
                       && User.IsInRole("Employee"))
                        {
                            <li class="main-btns nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">My Page</a>
                            </li>
                        }
                    </ul>


                </div>
                <ul class="navbar-nav float-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item  float-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:rgba(255, 255, 255, 90%)">
        <div class="container">
            &copy; 2021 - Hcm.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/hcm/js/js.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>