Hcm.Web/Models/EmployeeViewModel.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Hcm.Web.Models
{
    public class EmployeeViewModel
    {
        [Display(Name = "Id")]
        public string EmployeeId { get; set; }

        [Display(Name = "Avatar")]
        public string Avatar { get; set; }
        [Display(Name = "Avatar File")]
        public IFormFile AvatarFile { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Family Name")]
        public string LastName { get; set; }
        [Display(Name = "Phone")]
        public string Phone { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Country")]
        public string Country { get; set; }
        [Display(Name = "Address Line")]
        public string AddressLine { get; set; }
        [Display(Name = "Post Code")]
        public string PostCode { get; set; }
        [Display(Name = "City")]
        public string City { get; set; }

        public AssignmentViewModel[] Assignments { get; set; }
    }
}

Hcm.Web/Controllers/AssignmentController.cs
using Hcm.Api.Client;
using Hcm.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Hcm.Web.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly IDepartmentClient _departmentClient;
        private readonly IAssignmentClient _assignmentClient;

        public AssignmentController(
            IDepartmentClient departmentClient,
            IAssignmentClient assignmentClient)
        {
            _departmentClient = departmentClient;
            _assignmentClient = assignmentClient;
        }

        public async Task<ActionResult> Edit(
            [FromRoute] string id, 
            [FromQuery] string employeeId)
        {
            var result = await _assignmentClient.GetAsync(id);
            var departments = await _departmentClient.GetAllAsync();

            return View(new AssignmentViewModel
            {
                AssignmentId = result.Id,
                Amount = result.Sallary.Amount,
                Currency = result.Sallary.Currency,
                Name = departments
                    .Where(e => e.Id == result.DepartmentId)
                    .Select(e => e.Name)
                    .FirstOrDefault(),
                DepartmentId = result.DepartmentId,
                End = result.End,
                Start =result.Start,
                JobTitle = result.JobTitle
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [FromRoute] string id, 
            [FromQuery] string employeeId,
            [FromForm] AssignmentViewModel assignment)
        {
            var result = await _assignmentClient.PutAsync(id, new AssignmentUpdateDto
            {
                Start = assignment.Start.Value,
                JobTitle = assignment.JobTitle,
                End = assignment.End,
                Id = assignment.AssignmentId,
                Sallary = new SallaryDto
                {
                    Amount = assignment.Amount,
                    Currency = assignment.Currency,
                }
            });

            return RedirectToAction("Edit", "Employee", new { id = employeeId });
        }

        public async Task<ActionResult> Create(
           [FromQuery] string employeeId)
        {
            var departments = await _departmentClient.GetAllAsync();

            return View(new AssignmentViewModel
            {
                Departments = departments
                    .Select(e => (e.Id, e.Name))
                    .ToArray()
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [FromQuery] string employeeId,
            [FromForm] AssignmentViewModel assignment)
        {
            var result = await _assignmentClient.PostAsync(
                employeeId, assignment.DepartmentId, new AssignmentCreateDto
            {
                Start = assignment.Start.Value,
                JobTitle = assignment.JobTitle,
                End = assignment.End,
                Sallary = new SallaryDto
                {
                    Amount = assignment.Amount,
                    Currency = assignment.Currency,
                }
            });

            return RedirectToAction("Edit", "Employee", new { id = employeeId });
        }

        
    }
}

Hcm.Web/Controllers/EmployeeController.cs
using Hcm.Api.Client;
using Hcm.Web.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Hcm.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IDepartmentClient _departmentClient;
        private readonly IAssignmentClient _assignmentClient;
        private readonly IEmployeeClient _employeeClient;
        private IWebHostEnvironment _hostEnvironment;
        private readonly IConfiguration _configuration;

        public EmployeeController(
            IDepartmentClient departmentClient,
            IAssignmentClient assignmentClient,
            IEmployeeClient employeeClient,
            IWebHostEnvironment hostEnvironment,
            IConfiguration configuration)
        {
            _departmentClient = departmentClient;
            _assignmentClient = assignmentClient;
            _employeeClient = employeeClient;
            _hostEnvironment = hostEnvironment;
            _configuration = configuration;
        }

        // GET: EmployeeController
        public async Task<ActionResult> Index()
        {
            var employees = await _employeeClient.GetAllAsync();
            return View(employees
                .Select(e => new EmployeeViewModel
                {
                    EmployeeId = e.Id,
                    Country = e.Country,
                    Avatar = e.Avatar, 
                    AvatarFile=e.AvatarFile,
                    FirstName = e.FirstName,
                    LastName = e.LastName,
                    Email = e.Email
                }).ToArray());

        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [FromForm] EmployeeViewModel employeeViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                await _employeeClient.PostAsync(new EmployeeCreateDto
                {
                    Avatar = "",  
                    AvatarFile=null,
                    Email = employeeViewModel.Email,
                    AddressLine = employeeViewModel.AddressLine,
                    City = employeeViewModel.City,
                    Country = employeeViewModel.Country,
                    FirstName = employeeViewModel.FirstName,
                    LastName = employeeViewModel.LastName,
                    Phone = employeeViewModel.Phone,
                    PostCode = employeeViewModel.PostCode
                });

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // GET: EmployeeController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var result = await _employeeClient.GetAsync(id);
            var assignments = await _assignmentClient.GetByEmployeeAsync(id);
            var departments = await _departmentClient.GetAllAsync();

            return View(new EmployeeViewModel
            {
                Avatar = result.Avatar,
                AvatarFile=result.AvatarFile,
                EmployeeId =id,
                Country = result.Country,
                FirstName = result.FirstName,
                LastName = result.LastName,
                Email = result.Email,
                AddressLine = result.AddressLine,
                City = result.City,
                Phone = result.Phone,
                PostCode = result.PostCode,
                Assignments = assignments.Select(e => new AssignmentViewModel
                {
                    AssignmentId = e.Id,
                    Amount = e.Sallary.Amount,
                    Currency = e.Sallary.Currency,
                    Name = departments.FirstOrDefault(d => d.Id == e.DepartmentId)?.Name,
                    DepartmentId = e.DepartmentId,
                    End = e.End,
                    Start = e.Start,
                    JobTitle = e.JobTitle
                }).ToArray()
            });
        }

        // GET: EmployeeController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var result = await _employeeClient.GetAsync(id);
            var assignments = await _assignmentClient.GetByEmployeeAsync(id);
            var departments = await _departmentClient.GetAllAsync();

            EmployeeViewModel employeeview = new EmployeeViewModel()
                {
                    EmployeeId = id,
                    Avatar = result.Avatar,
                    AvatarFile = result.AvatarFile,
                    Country = result.Country,
                    FirstName = result.FirstName,
                    LastName = result.LastName,
                    Email = result.Email,
                    AddressLine = result.AddressLine,
                    City = result.City,
                    Phone = result.Phone,
                    PostCode = result.PostCode,
                    Assignments = assignments.Select(e => new AssignmentViewModel
                    {
                        AssignmentId = e.Id,
                        Amount = e.Sallary.Amount,
                        Currency = e.Sallary.Currency,
                        Name = departments.FirstOrDefault(d => d.Id == e.DepartmentId)?.Name,
                        DepartmentId = e.DepartmentId,
                        End = e.End,
                        Start = e.Start,
                        JobTitle = e.JobTitle
                    }).ToArray()
                };

            return View(employeeview);


        }
        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [FromRoute] string id,
             [FromForm] EmployeeViewModel employeeViewModel)
        {
            /*
            var old_result = await _employeeClient.GetAsync(id);
            var assignments = await _assignmentClient.GetByEmployeeAsync(id);
            var departments = await _departmentClient.GetAllAsync();*/
            try
            {
                //EmployeeDto originalEmployee = old_result;

                    string imagesPath = _configuration.GetValue<string>("AvatarLocation");

                    string directoryPath = Path.Combine(imagesPath, id);
                    if (!Directory.Exists(directoryPath))
                    {
                        Directory.CreateDirectory(directoryPath);
                    }
                    var files = Directory.GetFiles(directoryPath);
                    foreach (var file in files)
                    {
                        System.IO.File.Delete(file);
                    }

                    string fileName = string.Format($"{Path.GetFileName(employeeViewModel.AvatarFile.FileName)}");
                  //  originalEmployee.Avatar = fileName;
                    string filePath = Path.Combine(directoryPath, fileName);
                    using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                    {
                           employeeViewModel.AvatarFile.CopyTo(fileStream);
                    }
                employeeViewModel.Avatar = fileName;                

                //save changes
                var result = await _employeeClient.PutAsync(id, new EmployeeUpdateDto
                {
                    Country = employeeViewModel.Country,
                    Avatar=employeeViewModel.Avatar,
                    AvatarFile = employeeViewModel.AvatarFile,
                    FirstName = employeeViewModel.FirstName,
                    LastName = employeeViewModel.LastName,
                    Email = employeeViewModel.Email,
                    AddressLine = employeeViewModel.AddressLine,
                    City = employeeViewModel.City,
                    Phone = employeeViewModel.Phone,
                    PostCode = employeeViewModel.PostCode,
                });
                if (User.Identity.IsAuthenticated && User.IsInRole("Employee"))
                {
                    return RedirectToAction("Details", "Employee", new { id = id });
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var result = await _employeeClient.GetAsync(id);

            return View(new EmployeeViewModel
            {
                Avatar = result.Avatar,
                EmployeeId = result.Id,
                Country = result.Country,
                FirstName = result.FirstName,
                LastName = result.LastName,
                Email = result.Email,
                AddressLine = result.AddressLine,
                City = result.City,
                Phone = result.Phone,
                PostCode = result.PostCode
            });
        }

        // POST: EmployeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, IFormCollection formCollection)
        {
            try
            {
                string imagesPath = _configuration.GetValue<string>("AvatarLocation");

                string directoryPath = Path.Combine(imagesPath, id.ToString());
                if (Directory.Exists(directoryPath))
                {
                    var files = Directory.GetFiles(directoryPath);

Hcm.Web/Views/Employee/Create.cshtml
@model Hcm.Web.Models.EmployeeViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="card shadow mb-5">
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="PostCode" class="control-label"></label>
                    <input asp-for="PostCode" class="form-control" />
                    <span asp-validation-for="PostCode" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="AddressLine" class="control-label"></label>
                    <input asp-for="AddressLine" class="form-control" />
                    <span asp-validation-for="AddressLine" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12 ">
                    <input type="submit" value="Create" class="btn btn-primary btn-sm float-right hcm-btn" />
                    <a asp-action="Index" class="btn btn-primary float-right btn-sm mr-3 hcm-btn">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hcm.Web/Views/Employee/Delete.cshtml
@model Hcm.Web.Models.EmployeeViewModel

@{
    ViewData["Title"] = "Delete";
}
<div style="background-color:rgb(255, 255, 255); padding:30px">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div style="margin-left:15%">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EmployeeId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EmployeeId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Country)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Country)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AddressLine)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AddressLine)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PostCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PostCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>

</div>

Hcm.Web/Views/Employee/Details.cshtml
@model Hcm.Web.Models.EmployeeViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="card shadow mb-5">
    <div class="card-body">
        <div class="card-title">
            <h3>@Html.ValueFor(e => e.FirstName) @Html.ValueFor(e => e.LastName)</h3>
        </div>
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-4">
                    @if (Model.AvatarFile != null && Model.Avatar != "")
                    {
                        <img src="~/hcm/img/avatars/@Html.ValueFor(e => e.EmployeeId)/@Model.Avatar" sstyle="width:100px; margin-left:25%; " />
                    }
                    else
                    {
                        <img src="~/hcm/img/noavatar.png" sstyle="width:100px; margin-left:25%; " />

                    }
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label asp-for="Country" class="control-label"></label>
                    <input asp-for="Country" class="form-control" />
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="PostCode" class="control-label"></label>
                    <input asp-for="PostCode" class="form-control" />
                    <span asp-validation-for="PostCode" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="AddressLine" class="control-label"></label>
                    <input asp-for="AddressLine" class="form-control" />
                    <span asp-validation-for="AddressLine" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12 ">
                    <a asp-action="Edit" asp-route-id="@Html.ValueFor(e => e.EmployeeId)" class="btn btn-danger btn-sm float-right hcm-btn">Edit</a>

                </div>
            </div>
        </form>
    </div>
</div>

@(await Html.PartialAsync("_AssignmentListPartialView", Model.Assignments))


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hcm.Web/Views/Employee/Index.cshtml
@model IEnumerable<Hcm.Web.Models.EmployeeViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">
            <a asp-action="Create"
               class="btn btn-primary btn-sm float-right" style="padding:6px 20px">Create</a>
            <div class="text-center">
                <h3>Employees</h3>
            </div>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Avatar)
                    </th>
                    <th>
                        Names
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Country)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @if (item.Avatar != null)
                            {
                                <img src="~/hcm/img/@item.EmployeeId.ToString()/@item.Avatar" style=" width: 40px; border-radius: 25%;">
                            }
                            else
                            {
                                <img src="~/hcm/img/noavatar.png" style="width: 40px; border-radius: 25%;">
                            }
                        </td>  
              

                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.EmployeeId" class="btn btn-danger btn-sm float-right hcm-btn">Delete</a>
                            <a asp-action="Edit" asp-route-id="@item.EmployeeId" class="btn btn-info btn-sm float-right mr-2 hcm-btn">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Hcm.Web/Views/Employee/_AssignmentListPartialView.cshtml
@model IEnumerable<Hcm.Web.Models.AssignmentViewModel>


<div class="card shadow">
    <div class="card-body">
        <div class="card-title">
            @if (User.Identity.IsAuthenticated
       && User.IsInRole("Administrator"))
            {
                <a asp-action="Create"
                   asp-controller="Assignment"
                   asp-route-employeeId="@ViewContext.RouteData.Values["id"]"
                   class="btn btn-primary btn-sm float-right" style="width:30px;height:30px">+</a>
                   }
            <div class="text-center">
                <h3>Assignments</h3>
            </div>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.JobTitle)</th>
                    <th>@Html.DisplayNameFor(model => model.Start)</th>
                    <th>@Html.DisplayNameFor(model => model.End)</th>
                    <th>@Html.DisplayNameFor(model => model.Amount)</th>
                    <th>@Html.DisplayNameFor(model => model.Currency)</th>
                    <th></th>
                </tr>
            </thead>
            @if (User.Identity.IsAuthenticated
          && User.IsInRole("Administrator"))
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(e => item.Name)</td>
                        <td>@Html.DisplayFor(e => item.JobTitle)</td>
                        <td>@Html.DisplayFor(e => item.Start)</td>
                        <td>@Html.DisplayFor(e => item.End)</td>
                        <td>@Html.DisplayFor(e => item.Amount)</td>
                        <td>@Html.DisplayFor(e => item.Currency)</td>
                        <td>
                            <!--  <a asp-controller="Assignment" asp-action="Delete" class="btn btn-danger btn-sm float-right hcm-btn">Delete</a>-->
                            <a asp-controller="Assignment"
                               asp-action="Edit"
                               asp-route-id="@item.AssignmentId"
                               asp-route-employeeId="@ViewContext.RouteData.Values["id"]"
                               class="btn btn-info btn-sm float-right mr-2 hcm-btn">Edit</a>
                        </td>
                    </tr>
                }
            }
            @if (User.Identity.IsAuthenticated
          && User.IsInRole("Employee"))
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(e => item.Name)</td>
                        <td>@Html.DisplayFor(e => item.JobTitle)</td>
                        <td>@Html.DisplayFor(e => item.Start)</td>
                        <td>@Html.DisplayFor(e => item.End)</td>
                        <td>@Html.DisplayFor(e => item.Amount)</td>
                        <td>@Html.DisplayFor(e => item.Currency)</td>
                        <td>
                            <a asp-controller="Assignment"
                               asp-action="Edit"
                               asp-route-id="@item.AssignmentId"
                               asp-route-employeeId="@ViewContext.RouteData.Values["id"]"
                               class="btn btn-info btn-sm float-right mr-2 hcm-btn">View</a>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>